# Generated by Django 3.0.7 on 2020-06-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'Donation'), ('W', 'Withdraw'), ('P', 'Put')], max_length=1)),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time', models.DateTimeField(auto_now=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='money.Balance')),
            ],
        ),
    ]
